### ISSUE TITLE
Broken links on landing page

### ISSUE THREAD

**Issue by dbaluta** [open-education-hub/open-education-hub-site#20]
On landing page https://open-education-hub.github.io/ there seem to be some issues:

Discord link page doesn't seem to load -> https://bit.ly/OpenEduHub
Reddit link seems to be broken. Clicking on it i get `reddit: https://www.reddit.com/user/Open_Education_Hub` which browsers can't understand.

Good luck with the projects. Looks really good!

**Comment by lizababu** [comment]
Thanks for pointing these out! For me the Discord link page loads, can you please try in another browser?
